services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - FRONTEND_ORIGINS=http://localhost:3000
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
